Addresses and closes #33
cpignata/eimpact-icmp pull request #37
Opened 2024-07-14 00:38 UTC by jmparikh

Added extra clarification text for Why ICMP was chosen as a medium for transporting environmental sustainability information and close #33.

2024-07-14 09:51 UTC, mwelzl approved these changes
This is ok with me (and thanks!);  I'm not too fond of "it works very nicely"... I would remove "very nicely", but this is non-blocking to me  :-)

2024-07-15 21:07 UTC, cpignata requested changes

2024-07-15 21:07 UTC, cpignata commented on draft-pignataro-eimpact-icmp.xml
> +        protocols for administration and troubleshooting and it works very nicely
replace "very nicely" with "effectively" or similar.

2024-07-15 21:07 UTC, cpignata commented on draft-pignataro-eimpact-icmp.xml
> +        in not only an automated setting, but also in an on-demand setting for
in not only -> not only in

2024-07-15 22:39 UTC, jmparikh commented
Very valid point. "effectively" is way better than "very nicaly".
Have changed it.

2024-07-20 21:08 UTC, cpignata approved these changes

2024-08-12 08:42 UTC, merged