Addresses and Closes #34
cpignata/eimpact-icmp pull request #38
Opened 2024-07-15 20:35 UTC by jmparikh

Added a limitations section to add the limitation of not being able to append environmental information extensions to an Extended Echo Message, as stated in [RFC 8335](https://datatracker.ietf.org/doc/html/rfc8335#section-2) and https://datatracker.ietf.org/doc/draft-fenner-intarea-probe-clarification/

2024-07-15 21:07 UTC, cpignata submitted a review, later dismissed

2024-07-20 21:12 UTC, cpignata reviewed
Please see comment

2024-07-20 21:14 UTC, cpignata commented
@jmparikh, sorry I do not totally get the rational for this text.
First, looks like it is section 2 (not 2.1), that says:
   Section 7 of [RFC4884] defines the ICMP Extension Structure.  As per
   RFC 4884, the Extension Structure contains exactly one Extension
   Header followed by one or more objects.  When applied to the ICMP
   Extended Echo Request message, the ICMP Extension Structure MUST
   contain exactly one instance of the Interface Identification Object
   (see Section 2.1).

Therefore, there MUST be only one instance of the "Interface Identification Object". 
Agreed.
That does not mean or imply to me that there cannot be other objects :-) 

What did I miss?

Ron Bonica, that's your RFC. thoughts?

2024-07-20 23:20 UTC, jmparikh commented
@cpignata , thanks for this!
Hmm.. now that you pointed it out, it does make sense that there's nothing stopping us to add other instance of objects🤔🤔 (why did I not think of this? 🙃)

So, the Section 2 of draft-fenner-intarea-probe-clarification (which is supposed to update RFC 8335) is same as that of RFC 8335, but adds a new line:

   The ICMP Extension Structure does not cover the rest
   of the packet; **it ends at the end of the single Interface
   Identification Object, and what follows is simply optional data.**

So, I wrote the limitation text for our draft based on this. But now that you've mentioned, there shouldn't be a limitation/problem in adding a new extension object (like env info) to the ICMP Extended Echo Request message after the Interface ID Object and the "optional data" can always follow after that? So... no actual limitation?

2024-07-20 23:24 UTC, jmparikh commented
But now that you've pointed this out, and based on what my new thoughts are:

There shouldn't be a limitation/problem in adding a new extension object (like env info) to the ICMP Extended Echo Request message after the Interface ID Object? The "optional data" can always follow after that?

2024-07-20 23:56 UTC, mwelzl requested changes
A tiny suggestion - but otherwise I'm okay with this. Whether this is now useful or not, I'm confused about... I leave this for @cpignata and you to figure out and I'm okay with either merging or deleting this  :-)

2024-07-20 23:56 UTC, mwelzl commented on draft-pignataro-eimpact-icmp.xml
> +        append more than one extension obect to an Extended Echo, the extension
```suggestion
        append more than one extension object to an Extended Echo, the extension 
```

2026-07-19 16:29 UTC, cpignata approved these changes

2026-07-19 16:36 UTC, cpignata approved these changes

2026-07-19 16:36 UTC, merged

2026-07-19 16:54 UTC, jmparikh commented
@cpignata looks like we might have to update the Limitation section a bit.

The current limitation section is based on the RFC8335. Which indirectly states that no new Extension Objects can be appended to the Extended Echo.
```
RFC8335:

Section 7 of [RFC4884] defines the ICMP Extension Structure.  As per
   RFC 4884, the Extension Structure contains exactly one Extension
   Header followed by one or more objects.  When applied to the ICMP
   Extended Echo Request message, the ICMP Extension Structure MUST
   contain exactly one instance of the Interface Identification Object
   (see [Section 2.1]).
```
And this is what our draft refers to.

But, since the start of this PR, there have been a lot of discussions over at https://datatracker.ietf.org/doc/draft-ietf-intarea-rfc8335bis/04/ and this behavior has changed a bit.
```
RFC8335-bis

Section 7 of [RFC4884] defines the ICMP Extension Structure.  As per
   RFC 4884, the Extension Structure contains exactly one Extension
   Header followed by one or more objects.  When applied to the ICMP
   Extended Echo Request message, the Extension Object(s) define the
   operation to perform.  In the PROBE application, the ICMP Extension
   Structure MUST contain exactly one instance of the Interface
   Identification Object (Section 2.1), and the ICMP Extension Structure
   does not cover the rest of the packet; it ends at the end of the
   single Interface Identification Object, and what follows is simply
   optional data.  The behavior when it contains a different Extension
   Object is not defined by this memo.
   [I-D.ietf-6man-icmpv6-reflection] is an example of a document which
   defines a different Extension Object and the corresponding behavior.
```

And so, with the RFC8335-bis, either we don't need the limitation section, as the limitation of not being able to append an object to an Extended Echo Req, is limited to the PROBE application, or update the section to refer to the rfc8335-bis (i.e. allow adding objects behind the Extended Echo).

And, William's and my PoC appends our Enviro Info Object to the Extended Echo Req (which is legal, as per rfc8335-bis)

2026-07-19 17:22 UTC, jmparikh commented
Since this PR is closed, have opened a new PR: #49, for the same.