Address and Close #35
cpignata/eimpact-icmp pull request #39
Opened 2024-07-17 17:49 UTC by jmparikh

What's new:

- Added a new 64-bit "wide" Sub-Object format for Node and Component Throughput.
- Added a new section "Sub-Object Formats" to discuss the "whys" and "whens related to the new wide format
- Added some example to show how these two formats can work

(closes #35)
Please review it and suggest changes if there's room for improvement.

2024-07-20 23:14 UTC, mwelzl requested changes
This is great, many thanks!  See my small change requests.

2024-07-20 23:14 UTC, mwelzl commented on draft-pignataro-eimpact-icmp.xml
> +        10Tbps. Now this cannot be represented in a field wihich is only 32-bit long.
```suggestion
        10Tbps. This cannot be represented in a field which is only 32-bit long. 
```

2024-07-20 23:14 UTC, mwelzl commented on draft-pignataro-eimpact-icmp.xml
>            <c>Node Throughput</c>
```suggestion
          <c>Node Throughput Short</c>
```

2024-07-20 23:14 UTC, mwelzl commented on draft-pignataro-eimpact-icmp.xml
>            <c>Component-level Throughput</c>
```suggestion
          <c>Component-level Throughput Short</c>
```

2024-07-20 23:14 UTC, mwelzl commented on draft-pignataro-eimpact-icmp.xml
> +        Because a 32-bit field can only represent a max throughput of 4Gbps (2 ^ 32 BPS).
```suggestion
        A 32-bit field can only represent a max throughput of 4Gbps (2 ^ 32 BPS).
```

2024-07-20 23:14 UTC, mwelzl commented on draft-pignataro-eimpact-icmp.xml
> +        So, to address this, we chose to define another format, a wider, 64-bit Sub-Object
```suggestion
        To address this, we define another format, a wider, 64-bit Sub-Object
```

2024-07-20 23:14 UTC, mwelzl commented on draft-pignataro-eimpact-icmp.xml
> +        Now that we have put forward these two format options, here's how a device MUST
```suggestion
```

2024-07-20 23:14 UTC, mwelzl commented on draft-pignataro-eimpact-icmp.xml
> +        choose amongst the available format options. It is recommended that the device
```suggestion
        It is recommended that the device
```

2024-07-20 23:14 UTC, mwelzl commented on draft-pignataro-eimpact-icmp.xml
> +        Now that we have put forward these two format options, here's how a device MUST
This first sentence seems just unnecessary, sounds a bit too colloquial for my taste, and the MUST just creates confusion here, I think.

2024-07-20 23:14 UTC, mwelzl commented on draft-pignataro-eimpact-icmp.xml
> +        MUST append the "short" 32-bit Sub-Object. And when the component/node throughput
```suggestion
        would append the "short" 32-bit Sub-Object. When the component/node throughput
```

Let's avoid RFC 2119 style words in an example. And: I don't see why we need to be so strict.

2024-07-20 23:14 UTC, mwelzl commented on draft-pignataro-eimpact-icmp.xml
> +        exceeds 4Gbps, the device MUST append the "wide" 64-bit Sub-Object. This will
```suggestion
        exceeds 4Gbps, the device would append the "wide" 64-bit Sub-Object. This will 
```

2024-07-20 23:14 UTC, mwelzl commented on draft-pignataro-eimpact-icmp.xml
> +        Object. i.e. For if a device has two line cards, one has a throughput of 2Gbps
```suggestion
        Object. i.e. For example, if a device has two line cards, one with a throughput of 2Gbps 
```

2024-07-20 23:14 UTC, mwelzl commented on draft-pignataro-eimpact-icmp.xml
> +        and another has a throughput of 10Gbps and if the device would like to append
```suggestion
        and another which has a throughput of 10Gbps, and if the device would like to append
```

2024-07-20 23:14 UTC, mwelzl commented on draft-pignataro-eimpact-icmp.xml
> +        and also will be able to choose a Sub-Object with C-Type=7 for the line card with
```suggestion
        and will also be able to choose a Sub-Object with C-Type=7 for the line card with 
```

2024-07-20 23:14 UTC, mwelzl commented on draft-pignataro-eimpact-icmp.xml
> +            There's an in-depth discussion on why there are two formats,
```suggestion
            A discussion on why there are two formats,
```

2024-07-20 23:14 UTC, mwelzl commented on draft-pignataro-eimpact-icmp.xml
> +            chosen over the other, in <xref target="subobject-formats" />.
```suggestion
            chosen over the other, can be found in <xref target="subobject-formats" />.
```

I just didn't like the "There's an in-depth"... just a matter of taste

2024-08-12 08:48 UTC, cpignata approved these changes

2024-08-12 08:49 UTC, merged